apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-app
  template:
    metadata:
      labels:
        app: finance-app
    spec:
      containers:
      - name: finance-app
        image: akki5175/finance_me:6
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: finance-app-service
spec:
  type: NodePort
  selector:
    app: finance-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008
